version = 1

[[analyzers]]
name = "javascript"
enabled = true

[analyzers.meta]
eslint_enabled = true
prettier_enabled = true
environment = ["nodejs"]
skip_rules = ["JS-0128", "JS-0455"]

[[analyzers]]
name = "secrets"
enabled = true
